### ISSUE TITLE
Cancer cohort error

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/DementiaDusCohortDiagnostics#1]
@daniellenewby I got an error because this [definition](https://github.com/oxford-pharmacoepi/DementiaDusCohortDiagnostics/blob/main/1_InstantiateCohorts/Cohorts/malignantNeoplasmsExcludingNonMelanomaSkinCancer01.json ) is a concept set not a cohort. Could you please take a look?

**Comment by daniellenewby** [comment]
Hi - updated the cohort - there are two files now 1) original from last week and 2) updated hopefully to remove skin cancer codes. The json that was causing you problems I downloaded from OmopConceptSetLibrary for cancer excl skin cancer.

**Comment by edward-burn** [comment]
Thanks. I just rerun, but I think the second cancer cohort comes back with a zero count because it is [looking in the drug domain not the condition one](https://github.com/oxford-pharmacoepi/DementiaDusCohortDiagnostics/blob/14cb83b82b16c77e1810ce9b038927c46d227bbd/1_InstantiateCohorts/Cohorts/cancer_exc_skin2.json#L93).

**Comment by daniellenewby** [comment]
Morning, it still ran not sure why(!) but yes sorry i have updated it now to run in both the condition and observation:
![image](https://user-images.githubusercontent.com/16097637/168024484-276383f0-ae42-49e4-9ba2-1213aafc56a3.png)
